import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Landmark, ShieldCheck, WalletCards } from "lucide-react";
import { createMetadata } from "@/lib/site";

export const metadata = createMetadata({
  title: "Rupi Docs — Mainnet payment workflow",
  description: "Rupi Mainnet documentation for Stellar USDC invoices, Fireblocks custody, and Onramp settlement.",
  path: "/docs",
});

export default function DocsPage() {
  return <main className="docs-page"><header className="docs-topbar"><Link href="/" className="docs-brand"><span>Rupi</span></Link><nav><a href="/llms.txt">llms.txt</a><a href="/llms-full.txt">LLM full text</a><Link href="/">Back to site <ArrowUpRight size={15} /></Link></nav></header><div className="docs-shell"><article className="docs-article"><Link className="docs-back" href="/"><ArrowLeft size={15} />Rupi home</Link><div className="docs-eyebrow"><span />Stellar Mainnet · Product docs</div><h1>From invoice to verified settlement.</h1><p className="docs-lede">Rupi creates USD invoices paid in Stellar Mainnet USDC and offers staged INR cash-out through Onramp for verified users.</p><section className="docs-section"><div className="docs-section-heading"><span>01</span><div><p>Custody</p><h2>Fireblocks-controlled signing</h2></div></div><div className="docs-prose-grid"><div><ShieldCheck size={20}/><h3>No app-held seed</h3><p>Rupi stores a Fireblocks vault mapping, public Stellar address, approved asset IDs, and activation state—never a raw secret or decryptable signing material.</p></div><div><WalletCards size={20}/><h3>Mainnet asset validation</h3><p>Payment reconciliation validates the configured USDC issuer, destination, memo, operation ID, transaction result, and ledger time.</p></div></div></section><section className="docs-section"><div className="docs-section-heading"><span>02</span><div><p>Settlement</p><h2>Onramp owns KYC and INR payout</h2></div></div><div className="docs-prose-grid"><div><Landmark size={20}/><h3>Tokenized details</h3><p>KYC documents and full bank details are collected directly through Onramp-hosted flows. Rupi stores provider references and masked bank details only.</p></div><div><ShieldCheck size={20}/><h3>Verified states</h3><p>Provider webhooks are signature-checked and queued idempotently. Rupi marks a cash-out paid only when Onramp reports a verified payout.</p></div></div></section><section className="docs-section"><div className="docs-section-heading"><span>03</span><div><p>Release boundaries</p><h2>What is intentionally unavailable</h2></div></div><p>Yield, Blend integration, arbitrary withdrawals, and non-INR settlement are not part of the Mainnet launch. See <Link href="/legal/custody-risk">Custody & risk</Link> and <Link href="/legal/fees">Fee schedule</Link> for release disclosures.</p></section></article></div></main>;
}
